### ISSUE TITLE
Cover issues

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/jack-london_lost-face#1]
- missing cover.source.jpg: should be the original cover image you downloaded before creating cover.jpg
- cover text must be in ALL CAPS (except for the <title> tag)
- run `build-images` before committing any new cover or titlepage stuff to make sure everything gets into one commit

**Comment by samisiddiqui** [comment]
Resolved in https://github.com/samisiddiqui/jack-london_lost-face/commit/8df5da8441e21ed429f6da5ec94517ad570e1189
