### ISSUE TITLE
Titlepage issues

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/jack-london_lost-face#2]
- Text must be in ALL CAPS (except <title>)
- viewbox must be appropriate to exactly the height of the content plus some padding.  See https://raw.githubusercontent.com/standardebooks/abraham-merritt_the-moon-pool/master/images/titlepage.svg for a viewbox sizing appropriate for this cover
- Run `build-images` again after making all these changes

**Comment by samisiddiqui** [comment]
Resolved in https://github.com/samisiddiqui/jack-london_lost-face/commit/8df5da8441e21ed429f6da5ec94517ad570e1189
