### ISSUE TITLE
content.opf issues

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/jack-london_lost-face#3]
- remove extra white space from <dc:subject>
- <dc:subject> authority should be from the Gutenberg text you used
- duplicate IDs in <dc.subject>
- long-description must be in escaped xhtml.  You can do this by wrapping it in `<![CDATA[ ... ]]>` and running `clean`.  See any other content.opf for an example.
- don't use `<ul>` or `<li>` in long-description, please write prose.
- remove .html from LoC name authority links (this is surprising but the canonical URLs don't have .html)
- missing cover artist metadata (see any other content.opf file)

**Comment by samisiddiqui** [comment]
Resolved in https://github.com/samisiddiqui/jack-london_lost-face/commit/8df5da8441e21ed429f6da5ec94517ad570e1189
