### ISSUE TITLE
Final checks required

### ISSUE THREAD

**Issue by acabal** [samisiddiqui/jack-london_lost-face#8]
- Please run `typogrify` again as there is still some missing automated typograpy
- Once done, run `build --check` to build the ebook and validate it using `epubcheck`.  `epubcheck` must pass validation (it currently does not).

These should be your last steps, and then you should be done!

**Comment by samisiddiqui** [comment]
Resolved in https://github.com/samisiddiqui/jack-london_lost-face/commit/8df5da8441e21ed429f6da5ec94517ad570e1189
